start python motion_writefile.py 1
start python motion_writefile.py 2
start python motion_writefile.py 3
start python motion_writefile.py 4
start python motion_writefile.py 5
start python motion_writefile.py 6
start python motion_writefile.py 7
start python motion_writefile.py 8
start python motion_writefile.py 9
start python motion_writefile.py 10
