start python motion_writefile.py nole1
start python motion_writefile.py nole2
start python motion_writefile.py nole3
start python motion_writefile.py nole4
start python motion_writefile.py nole5
start python motion_writefile.py nole6
start python motion_writefile.py nole7
start python motion_writefile.py nole8
start python motion_writefile.py nole9
start python motion_writefile.py nole10
start python motion_writefile.py dawara
