start /min python motion_readfile.py nole1
start /min python motion_readfile.py nole2
start /min python motion_readfile.py nole3
start /min python motion_readfile.py nole4
start /min python motion_readfile.py nole5
start /min python motion_readfile.py nole6
start /min python motion_readfile.py nole7
start /min python motion_readfile.py nole8
start /min python motion_readfile.py nole9
start /min python motion_readfile.py nole10
start /min python motion_readfile.py nole11
start /min python motion_readfile.py dawara