start pythonw motion_writefile.py nole1
start pythonw motion_writefile.py nole2
start pythonw motion_writefile.py nole3
start pythonw motion_writefile.py nole4
start pythonw motion_writefile.py nole5
start pythonw motion_writefile.py nole6
start pythonw motion_writefile.py nole7
start pythonw motion_writefile.py nole8
start pythonw motion_writefile.py nole9
start pythonw motion_writefile.py nole10
start pythonw motion_writefile.py nole11
start pythonw motion_writefile.py dawara
