start /min python motion_writefile.py nole1
start /min python motion_writefile.py nole2
start /min python motion_writefile.py nole3
start /min python motion_writefile.py nole4
start /min python motion_writefile.py nole5
start /min python motion_writefile.py nole6
start /min python motion_writefile.py nole7
start /min python motion_writefile.py nole8
start /min python motion_writefile.py nole9
start /min python motion_writefile.py nole10
start /min python motion_writefile.py nole11
start /min python motion_writefile.py dawara