start pythonw motion_alert.py nole1
start pythonw motion_alert.py nole2
start pythonw motion_alert.py nole3
start pythonw motion_alert.py nole4
start pythonw motion_alert.py nole5
start pythonw motion_alert.py nole6
start pythonw motion_alert.py nole7
start pythonw motion_alert.py nole8
start pythonw motion_alert.py nole9
start pythonw motion_alert.py nole10
start pythonw motion_alert.py nole11
start pythonw motion_alert.py dawara
